<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Home_PC" ignored="0" name="HomePageTest" tests="4" failures="1" timestamp="18 Jan 2018 20:14:04 GMT" time="17.161" errors="0">
  <testcase name="verifyLoginWithInvalidCredentials" time="1.909" classname="com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
  <testcase name="verifyLoginWithInvalidCredentials" time="1.718" classname="com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
  <testcase name="verifyLoginWithInvalidCredentials" time="1.666" classname="com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
  <testcase name="verifyLoginWithInvalidCredentials" time="1.568" classname="com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials">
    <failure type="java.lang.AssertionError" message="expected [TestAuthentication failed.] but found [Authentication failed.]">
      <![CDATA[java.lang.AssertionError: expected [TestAuthentication failed.] but found [Authentication failed.]
	at com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials.verifyLoginWithInvalidCredentials(TC001_VerifyLoginWithInvalidCredentials.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
</testsuite> <!-- HomePageTest -->
